title: My personal blog - Ayush Karn
email: ayush@disroot.org
description: > # this means to ignore newlines until "baseurl:"
  This is my home on the web.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ayush Karn # add your name
author-pic: ayush-face.jpg
about-author:  My name is Ayush Karn. I’m an Engineering student from India.
                I develop mobile applications using the Flutter SDK.

# Contact links
email: ayush@disroot.org # Add your Email address
website: eldraco19.github.io # Add your website, do not add http://
linkedin: ayush-karn # Add your Linkedin handle
github: eldraco19 # Add your Github handle
twitter: '@_eldraco_' # Add your Twitter handle


# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
